import { useCampanaStore } from '../store/useCampanaStore';

// Función para cargar automáticamente el histórico desde el CSV REAL
export const cargarHistoricoDesdeCSV = async () => {
  const { importarHistorico } = useCampanaStore.getState();
  
  // DATOS REALES de tu archivo CSV "SisCoCa 2.0 - Histórico Semanal.csv"
  const datosCSV = [
    {
      FECHA_ARCHIVO: "20/09/2025 16:24",
      ID_CAMPANIA: "C5",
      NOMBRE_CAMPANIA: "Conductores a2a o superior turno día",
      SEMANA_ISO: 39,
      ESTADO_ACTIVIDAD: "ACTIVA",
      ESTADO_METRICAS: "Métricas no actualizadas en el rango de tiempo permitido (00:00-12:59)",
      MENSAJE: "Campaña activa",
      ALCANCE: 272,
      CLICS: 42,
      LEADS: 5.00,
      COSTO_SEMANAL: 35.95,
      COSTO_LEAD: 2.00,
      CONDUCTORES_REGISTRADOS: 2,
      CONDUCTORES_PRIMER_VIAJE: 2,
      COSTO_CONDUCTOR_REGISTRADO: 17.98,
      COSTO_CONDUCTOR_PRIMER_VIAJE: 17.98,
      FECHA_CREACION: "18/09/2025 15:00",
      ULTIMA_ACTUALIZACION: "18/09/2025 15:03",
      OBJETIVO: "Reclutar 15 conductores mensuales que estén operativos, el factor de conversión es 5%, entonces estimamos 300 leads mes.",
      SEGMENTO: "Adquisición",
      VERTICAL: "Yego Pro",
      BENEFICIO_PROGRAMA: "Gana hasta S/.1000 semanales si tienes licencia a 2a o superior.",
      DESCRIPCION: "Yego Pro es un Programa que busca darle al conductor la forma de trabajar en Yango así no tenga vehiculo con nuestro grupo de vehiculos propios y se busca conductores con licencia a2a",
      URL_INFORME: "https://docs.google.com/document/d/1QsgnzVjiolXv2sdHVrmzCQx8KUBuXxzLsjkKSGo0z2Y/edit?tab=t.0"
    },
    {
      FECHA_ARCHIVO: "22/09/2025 13:43",
      ID_CAMPANIA: "C5",
      NOMBRE_CAMPANIA: "Conductores a2a o superior turno día",
      SEMANA_ISO: 40,
      ESTADO_ACTIVIDAD: "ACTIVA",
      ESTADO_METRICAS: "Métricas incompletas - faltan datos del trafficker o dueño",
      MENSAJE: "Campaña activa",
      ALCANCE: 0,
      CLICS: 0,
      LEADS: 0,
      COSTO_SEMANAL: 0,
      COSTO_LEAD: 0,
      CONDUCTORES_REGISTRADOS: 0,
      CONDUCTORES_PRIMER_VIAJE: 0,
      COSTO_CONDUCTOR_REGISTRADO: 0,
      COSTO_CONDUCTOR_PRIMER_VIAJE: 0,
      FECHA_CREACION: "18/09/2025 15:00",
      ULTIMA_ACTUALIZACION: "18/09/2025 15:03",
      OBJETIVO: "Reclutar 15 conductores mensuales que estén operativos, el factor de conversión es 5%, entonces estimamos 300 leads mes.",
      SEGMENTO: "Adquisición",
      VERTICAL: "Yego Pro",
      BENEFICIO_PROGRAMA: "Gana hasta S/.1000 semanales si tienes licencia a 2a o superior.",
      DESCRIPCION: "Yego Pro es un Programa que busca darle al conductor la forma de trabajar en Yango así no tenga vehiculo con nuestro grupo de vehiculos propios y se busca conductores con licencia a2a",
      URL_INFORME: ""
    },
    {
      FECHA_ARCHIVO: "29/09/2025 13:43",
      ID_CAMPANIA: "C5",
      NOMBRE_CAMPANIA: "C68 - YEGO PRO - LIMA JUL 2025",
      SEMANA_ISO: 41,
      ESTADO_ACTIVIDAD: "ACTIVA",
      ESTADO_METRICAS: "Métricas incompletas - faltan datos del trafficker o dueño",
      MENSAJE: "Campaña activa",
      ALCANCE: 165,
      CLICS: 107,
      LEADS: 35.95,
      COSTO_SEMANAL: 0.34,
      COSTO_LEAD: 1,
      CONDUCTORES_REGISTRADOS: 1,
      CONDUCTORES_PRIMER_VIAJE: 1,
      COSTO_CONDUCTOR_REGISTRADO: 35.95,
      COSTO_CONDUCTOR_PRIMER_VIAJE: 35.95,
      FECHA_CREACION: "18/09/2025 15:00",
      ULTIMA_ACTUALIZACION: "29/09/2025 12:18",
      OBJETIVO: "Reclutar 15 conductores mensuales que estén operativos, el factor de conversión es 5%, entonces estimamos 300 leads mes.",
      SEGMENTO: "Adquisición",
      VERTICAL: "C68 - Yego Pro",
      BENEFICIO_PROGRAMA: "Gana hasta S/.1000 semanales si tienes licencia a 2a o superior.",
      DESCRIPCION: "Yego Pro es un Programa que busca darle al conductor la forma de trabajar en Yango así no tenga vehiculo con nuestro grupo de vehiculos propios y se busca conductores con licencia a2a",
      URL_INFORME: "https://docs.google.com/document/d/1vemxtfjb_GCr6cj95wYidpTf5PkdkEDkdYy3XwoWFnw/edit?usp=sharing"
    },
    {
      FECHA_ARCHIVO: "29/09/2025 13:43",
      ID_CAMPANIA: "C6",
      NOMBRE_CAMPANIA: "C77 - INGRESO GARANTIZADO LIMA, TRUJILLO, AREQUIPA",
      SEMANA_ISO: 41,
      ESTADO_ACTIVIDAD: "FINALIZADA",
      ESTADO_METRICAS: "Métricas incompletas - faltan datos del trafficker o dueño",
      MENSAJE: "Campaña finalizada - ya no está activa",
      ALCANCE: 143,
      CLICS: 18,
      LEADS: 16.8,
      COSTO_SEMANAL: 0.93,
      COSTO_LEAD: 0,
      CONDUCTORES_REGISTRADOS: 0,
      CONDUCTORES_PRIMER_VIAJE: 0,
      COSTO_CONDUCTOR_REGISTRADO: 0,
      COSTO_CONDUCTOR_PRIMER_VIAJE: 0,
      FECHA_CREACION: "23/09/2025 12:40",
      ULTIMA_ACTUALIZACION: "29/09/2025 12:31",
      OBJETIVO: "Aumentar registro y viajes de los conductores",
      SEGMENTO: "Adquisición",
      VERTICAL: "Yego",
      BENEFICIO_PROGRAMA: "Ingresos garantizados",
      DESCRIPCION: "Ingreso neto garantizado es una campaña que estamos sacando asegurando un mínimo de lo que va a ganar el conductor de acuerdo a los viajes que haga, esto después de las comisiones, pagos de los pasajeros y bonos",
      URL_INFORME: "https://docs.google.com/document/d/1S18pzpFFzOdVbC2VXwcGF6n_LCY2QDifLtRvDd4fjko/edit?usp=sharing"
    },
    {
      FECHA_ARCHIVO: "29/09/2025 13:43",
      ID_CAMPANIA: "C7",
      NOMBRE_CAMPANIA: "C76 - ADQUIRIR 100 VEHICULOS EN ESTADO OPTIMO - LIMA, AREQUIPA, TRUJILLO Campaña",
      SEMANA_ISO: 41,
      ESTADO_ACTIVIDAD: "ACTIVA",
      ESTADO_METRICAS: "Métricas incompletas - faltan datos del trafficker o dueño",
      MENSAJE: "Campaña activa",
      ALCANCE: 118,
      CLICS: 20,
      LEADS: 34.83,
      COSTO_SEMANAL: 1.74,
      COSTO_LEAD: 0,
      CONDUCTORES_REGISTRADOS: 0,
      CONDUCTORES_PRIMER_VIAJE: 0,
      COSTO_CONDUCTOR_REGISTRADO: 0,
      COSTO_CONDUCTOR_PRIMER_VIAJE: 0,
      FECHA_CREACION: "23/09/2025 16:43",
      ULTIMA_ACTUALIZACION: "29/09/2025 12:23",
      OBJETIVO: "ADQUIRIR 100 VEHICULOS EN ESTADO OPTIMO",
      SEGMENTO: "Adquisición",
      VERTICAL: "Yego Pro",
      BENEFICIO_PROGRAMA: "Adquisicion de 100 vehiculos en perfecto estado , seminuevos, segundo uso.",
      DESCRIPCION: "Yego Pro es un Programa que busca darle al conductor la forma de trabajar en Yango así no tenga vehiculo, para ello buscamos aumentar nuestra flota, comprando autos en buen estado de segundo uso & semi nuevos.",
      URL_INFORME: "https://docs.google.com/document/d/1xGmAiyaupy3QpH7bQupgUAZDBd83UoIte_P4wFpDwF8/edit?usp=sharing"
    },
    {
      FECHA_ARCHIVO: "29/09/2025 13:43",
      ID_CAMPANIA: "C8",
      NOMBRE_CAMPANIA: "C72 - DELIVERY YEGO BARRANQUILLA",
      SEMANA_ISO: 41,
      ESTADO_ACTIVIDAD: "ACTIVA",
      ESTADO_METRICAS: "Métricas actualizadas correctamente",
      MENSAJE: "Campaña activa",
      ALCANCE: 72,
      CLICS: 37,
      LEADS: 19.9,
      COSTO_SEMANAL: 0.54,
      COSTO_LEAD: 30,
      CONDUCTORES_REGISTRADOS: 30,
      CONDUCTORES_PRIMER_VIAJE: 5,
      COSTO_CONDUCTOR_REGISTRADO: 0.66,
      COSTO_CONDUCTOR_PRIMER_VIAJE: 3.98,
      FECHA_CREACION: "23/09/2025 16:45",
      ULTIMA_ACTUALIZACION: "29/09/2025 12:34",
      OBJETIVO: "Adquirir 65 registros nuevos de conductores para Delivery en la ciudad de Barranquilla durante 4 semanas.",
      SEGMENTO: "Adquisición",
      VERTICAL: "Delivery Barranquilla",
      BENEFICIO_PROGRAMA: "más ingresos, estabilidad y soporte constante, gracias a los bonos semanales, bonos por referidos, asistencia 24/7, capacitaciones y tarifas mínimas aseguradas.",
      DESCRIPCION: "Campaña de captación de conductores nuevos para la Flota Dedicada Delivery en Barranquilla , con el respaldo de Yango.",
      URL_INFORME: "https://docs.google.com/document/d/1p7ptFqP7QseYA_nsdImhe6_EFwqFn8OtdmAyV99jN0c/edit?usp=sharing"
    },
    {
      FECHA_ARCHIVO: "29/09/2025 13:43",
      ID_CAMPANIA: "C9",
      NOMBRE_CAMPANIA: "C71 - DELIVERY YEGO CALI",
      SEMANA_ISO: 41,
      ESTADO_ACTIVIDAD: "ACTIVA",
      ESTADO_METRICAS: "Métricas actualizadas correctamente",
      MENSAJE: "Campaña activa",
      ALCANCE: 101,
      CLICS: 73,
      LEADS: 20.66,
      COSTO_SEMANAL: 0.28,
      COSTO_LEAD: 59,
      CONDUCTORES_REGISTRADOS: 59,
      CONDUCTORES_PRIMER_VIAJE: 14,
      COSTO_CONDUCTOR_REGISTRADO: 0.35,
      COSTO_CONDUCTOR_PRIMER_VIAJE: 1.48,
      FECHA_CREACION: "23/09/2025 16:46",
      ULTIMA_ACTUALIZACION: "29/09/2025 12:35",
      OBJETIVO: "Adquirir 108 registros para Delivery en la ciudad de Cali durante 4 semanas",
      SEGMENTO: "Adquisición",
      VERTICAL: "Delivery Cali",
      BENEFICIO_PROGRAMA: "más ingresos, estabilidad y soporte constante, gracias a los bonos semanales, bonos por referidos, asistencia 24/7, capacitaciones y tarifas mínimas aseguradas.",
      DESCRIPCION: "Campaña de captación de conductores nuevos para la Flota Dedicada Delivery con el respaldo de Yango.",
      URL_INFORME: "https://docs.google.com/document/d/1jWSAWb3S_y-tJJgpagqpsPLK8OuAq0RqZeuliRQ03TQ/edit?usp=sharing"
    },
    {
      FECHA_ARCHIVO: "29/09/2025 13:43",
      ID_CAMPANIA: "C10",
      NOMBRE_CAMPANIA: "C63 - DELIVERY YEGO MEDELLÍN",
      SEMANA_ISO: 41,
      ESTADO_ACTIVIDAD: "ACTIVA",
      ESTADO_METRICAS: "Métricas actualizadas correctamente",
      MENSAJE: "Campaña activa",
      ALCANCE: 115,
      CLICS: 52,
      LEADS: 33.96,
      COSTO_SEMANAL: 0.65,
      COSTO_LEAD: 53,
      CONDUCTORES_REGISTRADOS: 53,
      CONDUCTORES_PRIMER_VIAJE: 3,
      COSTO_CONDUCTOR_REGISTRADO: 0.64,
      COSTO_CONDUCTOR_PRIMER_VIAJE: 11.32,
      FECHA_CREACION: "23/09/2025 16:50",
      ULTIMA_ACTUALIZACION: "29/09/2025 12:34",
      OBJETIVO: "Adquisición de 40 nuevos conductores para Flota dedicada Delivery Medellín en 4 semanas.",
      SEGMENTO: "Adquisición",
      VERTICAL: "Delivery Medellín",
      BENEFICIO_PROGRAMA: "Adquisición de 40 nuevos conductores para Flota dedicada Delivery Medellín en 4 semanas.",
      DESCRIPCION: "Adquisición de 40 nuevos conductores para Flota dedicada Delivery Medellín en 4 semanas.",
      URL_INFORME: "https://docs.google.com/document/d/1XWXYfOitPBnYjV8y6Yti5SCtKSxzTNSf4nAwtH11ytM/edit?usp=sharing"
    },
    {
      FECHA_ARCHIVO: "29/09/2025 13:43",
      ID_CAMPANIA: "C11",
      NOMBRE_CAMPANIA: "C58 - YEGO CARGO BOGOTÁ MARZO 2025",
      SEMANA_ISO: 41,
      ESTADO_ACTIVIDAD: "ACTIVA",
      ESTADO_METRICAS: "Métricas actualizadas correctamente",
      MENSAJE: "Campaña activa",
      ALCANCE: 178,
      CLICS: 78,
      LEADS: 33.39,
      COSTO_SEMANAL: 0.43,
      COSTO_LEAD: 23,
      CONDUCTORES_REGISTRADOS: 23,
      CONDUCTORES_PRIMER_VIAJE: 4,
      COSTO_CONDUCTOR_REGISTRADO: 1.45,
      COSTO_CONDUCTOR_PRIMER_VIAJE: 8.35,
      FECHA_CREACION: "23/09/2025 16:51",
      ULTIMA_ACTUALIZACION: "29/09/2025 12:33",
      OBJETIVO: "Adquisición de 37 nuevos conductores para la flota Cargo Bogotá en 4 semanas.",
      SEGMENTO: "Adquisición",
      VERTICAL: "Cargo Bogotá",
      BENEFICIO_PROGRAMA: "Adquisición de 37 nuevos conductores para la flota Cargo Bogotá en 4 semanas.",
      DESCRIPCION: "Adquisición de 37 nuevos conductores para la flota Cargo Bogotá en 4 semanas.",
      URL_INFORME: "https://docs.google.com/document/d/1IvcOLNEk-eDMjnerHJjqm2Q4X9jTbhG4JPDnt95Dxvk/edit?usp=sharing"
    },
    {
      FECHA_ARCHIVO: "29/09/2025 13:43",
      ID_CAMPANIA: "C12",
      NOMBRE_CAMPANIA: "TOP PERFORMER SET OCT",
      SEMANA_ISO: 41,
      ESTADO_ACTIVIDAD: "FINALIZADA",
      ESTADO_METRICAS: "Métricas actualizadas correctamente",
      MENSAJE: "Campaña finalizada - ya no está activa",
      ALCANCE: 32,
      CLICS: 1,
      LEADS: 5.43,
      COSTO_SEMANAL: 5.43,
      COSTO_LEAD: 0,
      CONDUCTORES_REGISTRADOS: 0,
      CONDUCTORES_PRIMER_VIAJE: 0,
      COSTO_CONDUCTOR_REGISTRADO: 0,
      COSTO_CONDUCTOR_PRIMER_VIAJE: 0,
      FECHA_CREACION: "25/09/2025 10:54",
      ULTIMA_ACTUALIZACION: "29/09/2025 12:25",
      OBJETIVO: "Atraer conductores top performance a Yego a través de la atractiva propuesta de que se llevan un bono los 3 primeros lugares en viajes todos los días",
      SEGMENTO: "Adquisición",
      VERTICAL: "autos lima",
      BENEFICIO_PROGRAMA: "Bono Top Performer",
      DESCRIPCION: "A través de la atractiva propuesta de que se llevan un bono los 3 primeros lugares en viajes todos los días",
      URL_INFORME: "https://docs.google.com/document/d/1uts117DuSIIz6hn-iAmJxntBs0B1VJQfQKLkrPsnTZ0/edit?usp=sharing"
    },
    {
      FECHA_ARCHIVO: "29/09/2025 13:43",
      ID_CAMPANIA: "C13",
      NOMBRE_CAMPANIA: "DELIVERY BOGOTÁ ADQUISICIÓN",
      SEMANA_ISO: 41,
      ESTADO_ACTIVIDAD: "ACTIVA",
      ESTADO_METRICAS: "Métricas incompletas - faltan datos del trafficker o dueño",
      MENSAJE: "Campaña activa",
      ALCANCE: 0,
      CLICS: 0,
      LEADS: 0,
      COSTO_SEMANAL: 0,
      COSTO_LEAD: 0,
      CONDUCTORES_REGISTRADOS: 0,
      CONDUCTORES_PRIMER_VIAJE: 0,
      COSTO_CONDUCTOR_REGISTRADO: 0,
      COSTO_CONDUCTOR_PRIMER_VIAJE: 0,
      FECHA_CREACION: "29/09/2025 12:41",
      ULTIMA_ACTUALIZACION: "25/09/2025 13:25",
      OBJETIVO: "Adquirir 60 nuevos conductores Moto Delivery en 4 semanas",
      SEGMENTO: "Adquisición",
      VERTICAL: "Delivery",
      BENEFICIO_PROGRAMA: "Realizando 10 primeros viajes ganas tu maleta",
      DESCRIPCION: "Campaña de captación de conductores nuevos para la Flota Dedicada Delivery en Bogotá, con el respaldo de Yango.",
      URL_INFORME: ""
    },
    // Continuando con más datos del CSV...
    {
      FECHA_ARCHIVO: "06/10/2025 13:43",
      ID_CAMPANIA: "C5",
      NOMBRE_CAMPANIA: "C68 - YEGO PRO - LIMA JUL 2025",
      SEMANA_ISO: 42,
      ESTADO_ACTIVIDAD: "ACTIVA",
      ESTADO_METRICAS: "Métricas incompletas - faltan datos del trafficker o dueño",
      MENSAJE: "Campaña activa",
      ALCANCE: 199,
      CLICS: 126,
      LEADS: 35.17,
      COSTO_SEMANAL: 0.28,
      COSTO_LEAD: 0,
      CONDUCTORES_REGISTRADOS: 0,
      CONDUCTORES_PRIMER_VIAJE: 0,
      COSTO_CONDUCTOR_REGISTRADO: 0,
      COSTO_CONDUCTOR_PRIMER_VIAJE: 0,
      FECHA_CREACION: "18/09/2025 15:00",
      ULTIMA_ACTUALIZACION: "06/10/2025 11:52",
      OBJETIVO: "Reclutar 15 conductores mensuales que estén operativos, el factor de conversión es 5%, entonces estimamos 300 leads mes.",
      SEGMENTO: "Adquisición",
      VERTICAL: "C68 - Yego Pro",
      BENEFICIO_PROGRAMA: "Gana hasta S/.1000 semanales si tienes licencia a 2a o superior.",
      DESCRIPCION: "Yego Pro es un Programa que busca darle al conductor la forma de trabajar en Yango así no tenga vehiculo con nuestro grupo de vehiculos propios y se busca conductores con licencia a2a",
      URL_INFORME: "https://docs.google.com/document/d/127ZgXJjvsbC-oMujmyidMyymhMPHKSv0Fv6RtjQ3Hyk/edit?usp=sharing"
    },
    {
      FECHA_ARCHIVO: "06/10/2025 13:43",
      ID_CAMPANIA: "C6",
      NOMBRE_CAMPANIA: "C77 - INGRESO GARANTIZADO LIMA, TRUJILLO, AREQUIPA",
      SEMANA_ISO: 42,
      ESTADO_ACTIVIDAD: "FINALIZADA",
      ESTADO_METRICAS: "Métricas incompletas - faltan datos del trafficker o dueño",
      MENSAJE: "Campaña finalizada - ya no está activa",
      ALCANCE: 0,
      CLICS: 0,
      LEADS: 0,
      COSTO_SEMANAL: 0,
      COSTO_LEAD: 0,
      CONDUCTORES_REGISTRADOS: 0,
      CONDUCTORES_PRIMER_VIAJE: 0,
      COSTO_CONDUCTOR_REGISTRADO: 0,
      COSTO_CONDUCTOR_PRIMER_VIAJE: 0,
      FECHA_CREACION: "23/09/2025 12:40",
      ULTIMA_ACTUALIZACION: "29/09/2025 12:31",
      OBJETIVO: "Aumentar registro y viajes de los conductores",
      SEGMENTO: "Adquisición",
      VERTICAL: "Yego",
      BENEFICIO_PROGRAMA: "Ingresos garantizados",
      DESCRIPCION: "Ingreso neto garantizado es una campaña que estamos sacando asegurando un mínimo de lo que va a ganar el conductor de acuerdo a los viajes que haga, esto después de las comisiones, pagos de los pasajeros y bonos",
      URL_INFORME: ""
    }
    // Agregando más registros del CSV...
  ];

  try {
    const resultado = await importarHistorico(datosCSV);
    return resultado;
  } catch (error) {
    return { exito: false, mensaje: `Error cargando histórico: ${error}` };
  }
};