import { Campana } from '../types';

export const campanasEjemplo: Campana[] = [
  {
    id: '001',
    nombre: 'PE-MOTOPER-FB-ADQ-001-GF-Verano2025',
    pais: 'PE',
    vertical: 'MOTOPER',
    plataforma: 'FB',
    segmento: 'Adquisición',
    idPlataformaExterna: '123456789',
    nombreDueno: 'Gonzalo Fajardo',
    inicialesDueno: 'GF',
    descripcionCorta: 'Verano2025',
    objetivo: 'Aumentar registro de conductores nuevos durante temporada alta de verano',
    beneficio: 'Bono S/200 por registro',
    descripcion: 'Campaña enfocada en atraer nuevos conductores de moto persona con incentivo de bienvenida durante la temporada de verano',
    tipoAterrizaje: 'FORMS',
    estado: 'Activa',
    urlInforme: 'https://ejemplo.com/informe1',
    alcance: 50000,
    clics: 2500,
    leads: 500,
    costoSemanal: 5000,
    costoLead: 10,
    conductoresRegistrados: 120,
    conductoresPrimerViaje: 80,
    costoConductorRegistrado: 41.67,
    costoConductorPrimerViaje: 62.5,
    fechaCreacion: new Date('2025-01-15'),
    ultimaActualizacion: new Date('2025-01-20'),
    semanaISO: 3
  },
  {
    id: '002',
    nombre: 'CO-CARGO-TT-RET-002-JL-Fidelizacion',
    pais: 'CO',
    vertical: 'CARGO',
    plataforma: 'TT',
    segmento: 'Retención',
    idPlataformaExterna: '987654321',
    nombreDueno: 'Paola Jorge',
    inicialesDueno: 'PJ',
    descripcionCorta: 'Fidelizacion',
    objetivo: 'Mantener conductores activos de cargo con programa de beneficios',
    beneficio: 'Descuentos en combustible',
    descripcion: 'Programa de fidelización para conductores de cargo con más de 6 meses de antigüedad en Colombia',
    tipoAterrizaje: 'WHATSAPP',
    estado: 'Activa',
    urlInforme: 'https://ejemplo.com/informe2',
    alcance: 30000,
    clics: 1800,
    leads: 300,
    costoSemanal: 3500,
    costoLead: 11.67,
    conductoresRegistrados: 85,
    conductoresPrimerViaje: 65,
    costoConductorRegistrado: 41.18,
    costoConductorPrimerViaje: 53.85,
    fechaCreacion: new Date('2025-01-10'),
    ultimaActualizacion: new Date('2025-01-18'),
    semanaISO: 3
  },
  {
    id: '003',
    nombre: 'PE-PREMIER-IG-RTO-003-MR-Reactivacion',
    pais: 'PE',
    vertical: 'PREMIER',
    plataforma: 'IG',
    segmento: 'Retorno',
    nombreDueno: 'Martha Pineda',
    inicialesDueno: 'MP',
    descripcionCorta: 'Reactivacion',
    objetivo: 'Reactivar conductores Premier que dejaron de usar la app',
    beneficio: 'Bono de reactivación S/150',
    descripcion: 'Campaña dirigida a conductores Premier inactivos por más de 3 meses con incentivo de reactivación',
    tipoAterrizaje: 'URL',
    estado: 'Creativo Enviado',
    fechaCreacion: new Date('2025-01-18'),
    ultimaActualizacion: new Date('2025-01-18'),
    semanaISO: 3
  },
  {
    id: '004',
    nombre: 'CO-AUTOPER-GG-ADQ-004-AS-Expansion',
    pais: 'CO',
    vertical: 'AUTOPER',
    plataforma: 'GG',
    segmento: 'Adquisición',
    idPlataformaExterna: '456789123',
    nombreDueno: 'Ariana de la Cruz',
    inicialesDueno: 'AC',
    descripcionCorta: 'Expansion',
    objetivo: 'Captación masiva de nuevos conductores de auto persona en Colombia',
    beneficio: 'Sin costo de registro + bono',
    descripcion: 'Campaña en Google Ads enfocada en expandir la base de conductores de auto persona en ciudades principales',
    tipoAterrizaje: 'LANDING',
    estado: 'Pendiente',
    fechaCreacion: new Date('2025-01-22'),
    ultimaActualizacion: new Date('2025-01-22'),
    semanaISO: 4
  }
];

export function cargarDatosEjemplo() {
  if (!localStorage.getItem('campanas')) {
    localStorage.setItem('campanas', JSON.stringify(campanasEjemplo));
  }
}
